/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projets5;

/**
 *
 * @author Lucas
 */
public class FenetreServeurGestUtil extends javax.swing.JFrame {

    /**
     * Creates new form FenetreServeurGestGroupe
     */
    public FenetreServeurGestUtil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paramGrLabel = new javax.swing.JLabel();
        listeGrList = new javax.swing.JScrollPane();
        listeUtilList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeGrUtilList = new javax.swing.JList<>();
        searchUtilField = new javax.swing.JTextField();
        supprUtilButton = new javax.swing.JButton();
        modifNomLabel = new javax.swing.JLabel();
        modifNomField = new javax.swing.JTextField();
        accepterButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ajoutGrUtilLabel = new javax.swing.JLabel();
        supprDuGroupeLabel = new javax.swing.JLabel();
        searchSupprGrField = new javax.swing.JTextField();
        ajoutGrField = new javax.swing.JTextField();
        retirerDuGrButton = new javax.swing.JButton();
        ajoutGrUtilButton = new javax.swing.JButton();
        modifPrenomLabel = new javax.swing.JLabel();
        modifPrenomField = new javax.swing.JTextField();
        modifMdpLabel = new javax.swing.JLabel();
        modifMdpField = new javax.swing.JTextField();
        confirmMdpLabel = new javax.swing.JLabel();
        confirmMdpField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paramGrLabel.setText("Liste des utilisateurs");
        getContentPane().add(paramGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 34, -1, -1));

        listeUtilList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeGrList.setViewportView(listeUtilList);

        getContentPane().add(listeGrList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 140));

        listeGrUtilList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listeGrUtilList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 130, 140));

        searchUtilField.setText("search");
        searchUtilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUtilFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchUtilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        supprUtilButton.setText("Supprimer");
        getContentPane().add(supprUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        modifNomLabel.setText("Nom :");
        getContentPane().add(modifNomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(modifNomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 120, -1));

        accepterButton.setText("Accepter");
        getContentPane().add(accepterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jButton1.setText("Annuler");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel1.setText("Liste des groupes de l'utilisateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        ajoutGrUtilLabel.setText("Ajouter un groupe pour l'utilisateur :");
        getContentPane().add(ajoutGrUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        supprDuGroupeLabel.setText("Supprimer du groupe :");
        getContentPane().add(supprDuGroupeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        searchSupprGrField.setText("search");
        getContentPane().add(searchSupprGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 80, -1));

        ajoutGrField.setText("search");
        getContentPane().add(ajoutGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 80, -1));

        retirerDuGrButton.setText("Supprimer");
        getContentPane().add(retirerDuGrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        ajoutGrUtilButton.setText("Ajouter");
        getContentPane().add(ajoutGrUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        modifPrenomLabel.setText("Prénom :");
        getContentPane().add(modifPrenomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(modifPrenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        modifMdpLabel.setText("Mot de passe :");
        getContentPane().add(modifMdpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        getContentPane().add(modifMdpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, -1));

        confirmMdpLabel.setText("Confirmer mot de passe :");
        getContentPane().add(confirmMdpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 20));
        getContentPane().add(confirmMdpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchUtilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUtilFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchUtilFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreServeurGestUtil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepterButton;
    private javax.swing.JTextField ajoutGrField;
    private javax.swing.JButton ajoutGrUtilButton;
    private javax.swing.JLabel ajoutGrUtilLabel;
    private javax.swing.JTextField confirmMdpField;
    private javax.swing.JLabel confirmMdpLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane listeGrList;
    private javax.swing.JList<String> listeGrUtilList;
    private javax.swing.JList<String> listeUtilList;
    private javax.swing.JTextField modifMdpField;
    private javax.swing.JLabel modifMdpLabel;
    private javax.swing.JTextField modifNomField;
    private javax.swing.JLabel modifNomLabel;
    private javax.swing.JTextField modifPrenomField;
    private javax.swing.JLabel modifPrenomLabel;
    private javax.swing.JLabel paramGrLabel;
    private javax.swing.JButton retirerDuGrButton;
    private javax.swing.JTextField searchSupprGrField;
    private javax.swing.JTextField searchUtilField;
    private javax.swing.JLabel supprDuGroupeLabel;
    private javax.swing.JButton supprUtilButton;
    // End of variables declaration//GEN-END:variables
}
