/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projets5;

/**
 *
 * @author Lucas
 */
public class FenetreServeurAccueil extends javax.swing.JFrame {

    /**
     * Creates new form FenetreServeurAccueil
     */
    public FenetreServeurAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creerGroupeButton = new javax.swing.JButton();
        supprModGroupeButton = new javax.swing.JButton();
        groupeLabel = new javax.swing.JLabel();
        utilLabel = new javax.swing.JLabel();
        creerUtilButton = new javax.swing.JButton();
        supprModUtilButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu serveur");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        creerGroupeButton.setText("Créer un groupe");
        creerGroupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerGroupeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creerGroupeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        supprModGroupeButton.setText("Supprimer / Modifier");
        supprModGroupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprModGroupeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supprModGroupeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        groupeLabel.setText("Gestion des groupes");
        getContentPane().add(groupeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        utilLabel.setText("Gestion des utilisateurs");
        getContentPane().add(utilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        creerUtilButton.setText("Créer un utilisateur");
        creerUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerUtilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creerUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        supprModUtilButton.setText("Supprimer / Modifier");
        supprModUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprModUtilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supprModUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jButton3.setText("Déconnexion");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerGroupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerGroupeButtonActionPerformed
        FenetreServeurCreerGr fenetre = new FenetreServeurCreerGr();
        fenetre.setVisible(true);
    }//GEN-LAST:event_creerGroupeButtonActionPerformed

    private void supprModGroupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprModGroupeButtonActionPerformed
        FenetreServeurGestGroupe fenetre = new FenetreServeurGestGroupe();
        fenetre.setVisible(true);
    }//GEN-LAST:event_supprModGroupeButtonActionPerformed

    private void creerUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerUtilButtonActionPerformed
        FenetreServeurCreerUtil fenetre = new FenetreServeurCreerUtil();
        fenetre.setVisible(true);
    }//GEN-LAST:event_creerUtilButtonActionPerformed

    private void supprModUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprModUtilButtonActionPerformed
        FenetreServeurGestUtil fenetre = new FenetreServeurGestUtil();
        fenetre.setVisible(true);
    }//GEN-LAST:event_supprModUtilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreServeurAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creerGroupeButton;
    private javax.swing.JButton creerUtilButton;
    private javax.swing.JLabel groupeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton supprModGroupeButton;
    private javax.swing.JButton supprModUtilButton;
    private javax.swing.JLabel utilLabel;
    // End of variables declaration//GEN-END:variables
}
