/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projets5;

/**
 *
 * @author Lucas
 */
public class FenetreServeurCreerGr extends javax.swing.JFrame {

    /**
     * Creates new form FenetreServeurCreerGr
     */
    public FenetreServeurCreerGr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomGrLabel = new javax.swing.JLabel();
        nomGrField = new javax.swing.JTextField();
        ajouterUtilLabel = new javax.swing.JLabel();
        searchUtilField = new javax.swing.JTextField();
        ajouterGroupeLabel = new javax.swing.JLabel();
        searchGroupeField = new javax.swing.JTextField();
        paramGrLabel = new javax.swing.JLabel();
        listeUtilGrLabel = new javax.swing.JLabel();
        listeUtilList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        supprUtilLabel = new javax.swing.JLabel();
        searchSupprUtilField = new javax.swing.JTextField();
        supprimerUtilButton = new javax.swing.JButton();
        creerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomGrLabel.setText("Nom du groupe :");
        getContentPane().add(nomGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(nomGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, -1));

        ajouterUtilLabel.setText("Ajouter un utilisateur :");
        getContentPane().add(ajouterUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        searchUtilField.setText("search");
        getContentPane().add(searchUtilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, -1));

        ajouterGroupeLabel.setText("Ajouter un groupe : ");
        getContentPane().add(ajouterGroupeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        searchGroupeField.setText("search");
        getContentPane().add(searchGroupeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        paramGrLabel.setText("Paramètres du groupe");
        getContentPane().add(paramGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        listeUtilGrLabel.setText("Liste des utilisateurs du groupe");
        getContentPane().add(listeUtilGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeUtilList.setViewportView(jList1);

        getContentPane().add(listeUtilList, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 170, 180));

        supprUtilLabel.setText("Supprimer un utilisateur :");
        getContentPane().add(supprUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        searchSupprUtilField.setText("search");
        getContentPane().add(searchSupprUtilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, -1));

        supprimerUtilButton.setText("Supprimer");
        getContentPane().add(supprimerUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        creerButton.setText("jButton1");
        getContentPane().add(creerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        annulerButton.setText("Annuler");
        getContentPane().add(annulerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreServeurCreerGr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajouterGroupeLabel;
    private javax.swing.JLabel ajouterUtilLabel;
    private javax.swing.JButton annulerButton;
    private javax.swing.JButton creerButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel listeUtilGrLabel;
    private javax.swing.JScrollPane listeUtilList;
    private javax.swing.JTextField nomGrField;
    private javax.swing.JLabel nomGrLabel;
    private javax.swing.JLabel paramGrLabel;
    private javax.swing.JTextField searchGroupeField;
    private javax.swing.JTextField searchSupprUtilField;
    private javax.swing.JTextField searchUtilField;
    private javax.swing.JLabel supprUtilLabel;
    private javax.swing.JButton supprimerUtilButton;
    // End of variables declaration//GEN-END:variables
}
