/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import modele.Groupe;
import modele.Utilisateur;
import serveur.Serveur;

/**
 *
 * @author Lucas
 */
public class FenetreServeurGestUtil extends javax.swing.JFrame {

    private DefaultListModel listeModeleUtil;
    private DefaultListModel listeModeleGr;
    private DefaultComboBoxModel comboGrModele;
    private Utilisateur utilSelect;
    private boolean utilModifie;
    private List<String> listeGr;
    private Serveur serveur;
    /**
     * Creates new form FenetreServeurGestGroupe
     */
    public FenetreServeurGestUtil(Serveur serveur) {
        this.serveur = serveur;
        utilSelect = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paramGrLabel = new javax.swing.JLabel();
        listeGrList = new javax.swing.JScrollPane();
        listeUtilList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeGrUtilList = new javax.swing.JList<>();
        searchUtilField = new javax.swing.JTextField();
        supprUtilButton = new javax.swing.JButton();
        modifNomLabel = new javax.swing.JLabel();
        modifNomField = new javax.swing.JTextField();
        accepterButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ajoutGrUtilLabel = new javax.swing.JLabel();
        supprDuGroupeLabel = new javax.swing.JLabel();
        searchSupprGrField = new javax.swing.JTextField();
        searchAjoutGrField = new javax.swing.JTextField();
        retirerGrButton = new javax.swing.JButton();
        ajoutGrUtilButton = new javax.swing.JButton();
        modifPrenomLabel = new javax.swing.JLabel();
        modifPrenomField = new javax.swing.JTextField();
        modifMdpLabel = new javax.swing.JLabel();
        confirmMdpLabel = new javax.swing.JLabel();
        searchUtilLabel = new javax.swing.JLabel();
        searchSupprGrLabel = new javax.swing.JLabel();
        ajoutGrCombo = new javax.swing.JComboBox<>();
        modifMdpField = new javax.swing.JPasswordField();
        modifMdpConfirmField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion d'utilisateurs");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paramGrLabel.setText("Liste des utilisateurs");
        getContentPane().add(paramGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 34, -1, -1));

        listeUtilList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        setListeModelUtil();
        listeUtilList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeUtilListValueChanged(evt);
            }
        });
        listeGrList.setViewportView(listeUtilList);

        getContentPane().add(listeGrList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 140));

        listeGrUtilList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listeGrUtilList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 190, 140));

        searchUtilField.setText("search");
        searchUtilField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchUtilFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchUtilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, -1));

        supprUtilButton.setText("Supprimer");
        supprUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprUtilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supprUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        modifNomLabel.setText("Nom :");
        getContentPane().add(modifNomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(modifNomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 120, -1));

        accepterButton.setText("Accepter");
        accepterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(accepterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 382, -1, -1));

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(annulerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 382, -1, -1));

        jLabel1.setText("Liste des groupes de l'utilisateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        ajoutGrUtilLabel.setText("Ajouter un groupe pour l'utilisateur :");
        getContentPane().add(ajoutGrUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        supprDuGroupeLabel.setText("Supprimer du groupe :");
        getContentPane().add(supprDuGroupeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        searchSupprGrField.setText("search");
        searchSupprGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchSupprGrFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchSupprGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 80, -1));

        searchAjoutGrField.setText("search");
        searchAjoutGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAjoutGrFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchAjoutGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 80, -1));

        retirerGrButton.setText("Supprimer");
        retirerGrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerGrButtonActionPerformed(evt);
            }
        });
        getContentPane().add(retirerGrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        ajoutGrUtilButton.setText("Ajouter");
        getContentPane().add(ajoutGrUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        modifPrenomLabel.setText("Prénom :");
        getContentPane().add(modifPrenomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(modifPrenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        modifMdpLabel.setText("Mot de passe :");
        getContentPane().add(modifMdpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        confirmMdpLabel.setText("Confirmer mot de passe :");
        getContentPane().add(confirmMdpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 349, -1, 20));

        searchUtilLabel.setText("Recherche");
        getContentPane().add(searchUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, -1));

        searchSupprGrLabel.setText("Recherche");
        getContentPane().add(searchSupprGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 160, -1));

        ajoutGrCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboGrModele = new DefaultComboBoxModel();
        setComboGrModel();
        getContentPane().add(ajoutGrCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 349, 180, -1));

        modifMdpField.setText("jPasswordField1");
        getContentPane().add(modifMdpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, -1));

        modifMdpConfirmField.setText("jPasswordField2");
        getContentPane().add(modifMdpConfirmField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void searchUtilFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchUtilFieldKeyReleased
        String text = searchUtilField.getText();        
        searchJList(text, listeUtilList, searchUtilLabel);
    }//GEN-LAST:event_searchUtilFieldKeyReleased

    private void searchSupprGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchSupprGrFieldKeyReleased
        String text = searchSupprGrField.getText();
        searchJList(text, listeGrUtilList, searchSupprGrLabel);
    }//GEN-LAST:event_searchSupprGrFieldKeyReleased

    private void searchAjoutGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAjoutGrFieldKeyReleased
        String text = searchAjoutGrField.getText();
        searchCombo(text, ajoutGrCombo); 
    }//GEN-LAST:event_searchAjoutGrFieldKeyReleased

    private void supprUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprUtilButtonActionPerformed
        int indUtil = listeUtilList.getSelectedIndex();
        Utilisateur utilSelect = (Utilisateur) listeModeleUtil.get(indUtil);
        //Le serveur supprime
        serveur.supprimerUtilisateur(utilSelect.getIdUtilisateur());        
        listeModeleUtil.removeElement(utilSelect);
        listeUtilList.setModel(listeModeleUtil);              
    }//GEN-LAST:event_supprUtilButtonActionPerformed

    private void listeUtilListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeUtilListValueChanged
        if((utilSelect != null) && utilModifie){
            int response = JOptionPane.showConfirmDialog(null, "Voulez-vous sauvegarder les modifications ?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                //On dit au serveur de modifier
                String mdp = new String(modifMdpField.getPassword());
                serveur.modificationUtilisateur(utilSelect.getIdUtilisateur(), modifNomField.getText(), modifPrenomField.getText(), mdp , listeGr);
            }            
        }
        //On affiche les groupes du nouvel user selectionne
        utilModifie = false;
        listeGr.removeAll(listeGr);
        int indSelect = listeUtilList.getSelectedIndex();
        utilSelect = (Utilisateur) listeModeleUtil.get(indSelect);
        //On affiche la liste du nouveau groupe selectionné
        setListeModelGr();
    }//GEN-LAST:event_listeUtilListValueChanged

    private void retirerGrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerGrButtonActionPerformed
        //groupe selectionné
        int index = listeGrUtilList.getSelectedIndex();
        //util selectionné
        int indUtil = listeUtilList.getSelectedIndex();
        Utilisateur utilSelect = (Utilisateur) listeModeleUtil.get(indUtil);
        listeModeleGr.remove(index);
        listeGrUtilList.setModel(listeModeleGr);        
        //On supprime le groupe de la liste
        listeGr.remove(index);        
        
    }//GEN-LAST:event_retirerGrButtonActionPerformed

    private void accepterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepterButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Voulez-vous sauvegarder les modifications ?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            String nom = modifNomField.getText();
            String prenom = modifPrenomField.getText();
            String mdp = new String(modifMdpField.getPassword());
            String mdpC = new String(modifMdpConfirmField.getPassword());
            //Verifications
            if(!nom.isEmpty() && !prenom.isEmpty() && !mdp.isEmpty() && mdp.equals(mdpC)){
               //On dit au serveur de modifier
               serveur.modificationUtilisateur(utilSelect.getIdUtilisateur(), nom, prenom, mdp , listeGr);
            }
            else {
                JOptionPane.showMessageDialog(null, "Erreurs dans les champs");
            }
            
            
        }
    }//GEN-LAST:event_accepterButtonActionPerformed
    public void searchJList(String text, JList liste, JLabel label) {
        
        // Get number of items in the list
        int size = liste.getModel().getSize();
        // Get all item objects
        for (int i = 0; i < size; i++) {
            String item = (String) liste.getModel().getElementAt(i);
            if(item.contains(text)) {
            int index = i;
            liste.setSelectedIndex(index);
            label.setText(text + " trouvé à l'index " + index);
            //Une fois trouvé, on arrête la boucle
            i = size +1;
            } else {
                liste.clearSelection();
                label.setText(text + " non trouvé");
            }
        }        
    }
    
    public void searchCombo(String text, JComboBox box) {
        
        // Get number of items in the list
        int size = box.getModel().getSize();
        
        // Get all item objects
        for (int i = 0; i < size; i++) {
            String item = (String) box.getModel().getElementAt(i);
            if(item.contains(text)) {
            int index = i;
            box.setSelectedIndex(index);
            //label.setText(text + " trouvé à l'index " + index);
            //Une fois trouvé, on arrête la boucle
            i = size +1;
            } else {
                //label.setText(text + " non trouvé");
            }
        }        
    }
    private void setListeModelGr(){
        int indUtil = listeUtilList.getSelectedIndex();
        if(indUtil != -1){
            utilSelect = (Utilisateur) listeModeleUtil.get(indUtil);
            List<Groupe> groupes = serveur.groupesUtilisateur(utilSelect.getIdUtilisateur());
            //Ajout de chaque groupe dans la JList
            for(Groupe gr : groupes){
                listeModeleGr.addElement(gr);
                listeGr.add(gr.getIdGroupe());
            }
            listeGrUtilList.setModel(listeModeleGr);
        }
                
    }
    
    private void setListeModelUtil(){
        
        Set<Utilisateur> utils = serveur.getUtilisateurs();
        //Ajout de chaque utilisateur dans la JList
        for(Utilisateur ut : utils){
            listeModeleUtil.addElement(ut);                       
        }
        listeUtilList.setModel(listeModeleUtil);
    }
    
    private void setComboGrModel(){
        
        Set<String> groupes = serveur.getGroupes();
        comboGrModele = new DefaultComboBoxModel();
        for(String gr : groupes){
            comboGrModele.addElement(gr);
        }
        ajoutGrCombo.setModel(comboGrModele);        
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepterButton;
    private javax.swing.JComboBox<String> ajoutGrCombo;
    private javax.swing.JButton ajoutGrUtilButton;
    private javax.swing.JLabel ajoutGrUtilLabel;
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel confirmMdpLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane listeGrList;
    private javax.swing.JList<String> listeGrUtilList;
    private javax.swing.JList<String> listeUtilList;
    private javax.swing.JPasswordField modifMdpConfirmField;
    private javax.swing.JPasswordField modifMdpField;
    private javax.swing.JLabel modifMdpLabel;
    private javax.swing.JTextField modifNomField;
    private javax.swing.JLabel modifNomLabel;
    private javax.swing.JTextField modifPrenomField;
    private javax.swing.JLabel modifPrenomLabel;
    private javax.swing.JLabel paramGrLabel;
    private javax.swing.JButton retirerGrButton;
    private javax.swing.JTextField searchAjoutGrField;
    private javax.swing.JTextField searchSupprGrField;
    private javax.swing.JLabel searchSupprGrLabel;
    private javax.swing.JTextField searchUtilField;
    private javax.swing.JLabel searchUtilLabel;
    private javax.swing.JLabel supprDuGroupeLabel;
    private javax.swing.JButton supprUtilButton;
    // End of variables declaration//GEN-END:variables
}
