/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.Observable;
import java.util.Observer;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import modele.Utilisateur;
import serveur.Serveur;

/**
 *
 * @author Lucas
 */
public class FenetreServeurAccueil extends javax.swing.JFrame implements Observer{
    private Serveur serveur;
    private DefaultListModel listeModele;
    /**
     * Creates new form FenetreServeurAccueil
     */
    public FenetreServeurAccueil(Serveur serveur) {
        this.serveur = serveur;
        this.serveur.addObserver(this);
        initComponents();
        ImageIcon img = new ImageIcon("icon.jpg");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        creerGroupeButton = new javax.swing.JButton();
        supprModGroupeButton = new javax.swing.JButton();
        groupeLabel = new javax.swing.JLabel();
        utilLabel = new javax.swing.JLabel();
        creerUtilButton = new javax.swing.JButton();
        supprModUtilButton = new javax.swing.JButton();
        decoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeConnectList = new javax.swing.JList<>();
        utilConnectLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil serveur");
        setMinimumSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        creerGroupeButton.setText("Créer un groupe");
        creerGroupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerGroupeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 31, 0, 0);
        getContentPane().add(creerGroupeButton, gridBagConstraints);

        supprModGroupeButton.setText("Supprimer / Modifier");
        supprModGroupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprModGroupeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 30, 0, 0);
        getContentPane().add(supprModGroupeButton, gridBagConstraints);

        groupeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        groupeLabel.setText("Gestion des groupes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 40, 0, 0);
        getContentPane().add(groupeLabel, gridBagConstraints);

        utilLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        utilLabel.setText("Gestion des utilisateurs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 56, 0, 0);
        getContentPane().add(utilLabel, gridBagConstraints);

        creerUtilButton.setText("Créer un utilisateur");
        creerUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerUtilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 56, 0, 0);
        getContentPane().add(creerUtilButton, gridBagConstraints);

        supprModUtilButton.setText("Supprimer / Modifier");
        supprModUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprModUtilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 56, 0, 0);
        getContentPane().add(supprModUtilButton, gridBagConstraints);

        decoButton.setText("Déconnexion");
        decoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 127, 0, 0);
        getContentPane().add(decoButton, gridBagConstraints);

        listeConnectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        setListConnModel();
        jScrollPane1.setViewportView(listeConnectList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = 167;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(13, 87, 0, 13);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        utilConnectLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        utilConnectLabel.setText("Utilisateurs en ligne");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 97, 0, 0);
        getContentPane().add(utilConnectLabel, gridBagConstraints);

        refreshButton.setText("Rafraichir");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 117, 26, 0);
        getContentPane().add(refreshButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenue sur le serveur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 36, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerGroupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerGroupeButtonActionPerformed
        FenetreServeurCreerGr fenetre = new FenetreServeurCreerGr(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_creerGroupeButtonActionPerformed

    private void supprModGroupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprModGroupeButtonActionPerformed
        FenetreServeurGestGroupe fenetre = new FenetreServeurGestGroupe(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_supprModGroupeButtonActionPerformed

    private void creerUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerUtilButtonActionPerformed
        FenetreServeurCreerUtil fenetre = new FenetreServeurCreerUtil(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_creerUtilButtonActionPerformed

    private void supprModUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprModUtilButtonActionPerformed
        FenetreServeurGestUtil fenetre = new FenetreServeurGestUtil(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_supprModUtilButtonActionPerformed

    private void decoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoButtonActionPerformed
        serveur.deconnecterServeur();
        FenetreServeurConnexion fen = new FenetreServeurConnexion();
        fen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_decoButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        listeModele.removeAllElements();
        setListConnModel();
    }//GEN-LAST:event_refreshButtonActionPerformed
    private void setListConnModel(){
        listeModele = new DefaultListModel();
        Set<Utilisateur> utilCo = serveur.utilisateursConnectes();
        for(Utilisateur ut : utilCo){
            listeModele.addElement(ut);
        }
        listeConnectList.setModel(listeModele);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creerGroupeButton;
    private javax.swing.JButton creerUtilButton;
    private javax.swing.JButton decoButton;
    private javax.swing.JLabel groupeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeConnectList;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton supprModGroupeButton;
    private javax.swing.JButton supprModUtilButton;
    private javax.swing.JLabel utilConnectLabel;
    private javax.swing.JLabel utilLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        setListConnModel();
    }
}
