/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Lucas
 */
public class FenetreServeurGestGroupe extends javax.swing.JFrame {
    private DefaultListModel listeModeleUtil;
    private DefaultListModel listeModeleGr;
    /**
     * Creates new form FenetreServeurGestGroupe
     */
    public FenetreServeurGestGroupe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paramGrLabel = new javax.swing.JLabel();
        listeGrList = new javax.swing.JScrollPane();
        listeGroupeList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeUtilGrList = new javax.swing.JList<>();
        searchGrField = new javax.swing.JTextField();
        supprGrButton = new javax.swing.JButton();
        modifNomLabel = new javax.swing.JLabel();
        modifNomField = new javax.swing.JTextField();
        accepterButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ajoutUtilGrLabel = new javax.swing.JLabel();
        ajoutGrUtilLabel = new javax.swing.JLabel();
        supprDuGroupeLabel = new javax.swing.JLabel();
        searchRetirerDuGrField = new javax.swing.JTextField();
        searchAjoutUtilGrField = new javax.swing.JTextField();
        searchAjoutGrUtilField = new javax.swing.JTextField();
        retirerDuGrButton = new javax.swing.JButton();
        ajoutUtilGrButton = new javax.swing.JButton();
        ajoutGrUtilButton = new javax.swing.JButton();
        searchGrLabel = new javax.swing.JLabel();
        searchUtilLabel = new javax.swing.JLabel();
        searchUtilAjoutCombo = new javax.swing.JComboBox<>();
        searchGrAjoutCombo = new javax.swing.JComboBox<>();
        modifierButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de groupes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paramGrLabel.setText("Liste des groupes");
        getContentPane().add(paramGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 34, -1, -1));

        listeGroupeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeModeleGr = new DefaultListModel();
        setListeModelGr();
        listeGrList.setViewportView(listeGroupeList);

        getContentPane().add(listeGrList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 140));

        listeUtilGrList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeModeleUtil = new DefaultListModel();
        setListeModelUtil();
        jScrollPane1.setViewportView(listeUtilGrList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 130, 140));

        searchGrField.setText("search");
        searchGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchGrFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, -1));

        supprGrButton.setText("Supprimer");
        supprGrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprGrButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supprGrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        modifNomLabel.setText("Modifier le nom :");
        getContentPane().add(modifNomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        getContentPane().add(modifNomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 80, -1));

        accepterButton.setText("Accepter");
        getContentPane().add(accepterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(annulerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel1.setText("Liste des utilisateurs du groupe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        ajoutUtilGrLabel.setText("Ajouter un utilisateur au groupe :");
        getContentPane().add(ajoutUtilGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        ajoutGrUtilLabel.setText("Ajouter un groupe pour l'utilisateur :");
        getContentPane().add(ajoutGrUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        supprDuGroupeLabel.setText("Supprimer du groupe :");
        getContentPane().add(supprDuGroupeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        searchRetirerDuGrField.setText("search");
        searchRetirerDuGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchRetirerDuGrFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchRetirerDuGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 80, -1));

        searchAjoutUtilGrField.setText("search");
        searchAjoutUtilGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAjoutUtilGrFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchAjoutUtilGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 80, -1));

        searchAjoutGrUtilField.setText("search");
        searchAjoutGrUtilField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAjoutGrUtilFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchAjoutGrUtilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 80, -1));

        retirerDuGrButton.setText("Supprimer");
        getContentPane().add(retirerDuGrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        ajoutUtilGrButton.setText("Ajouter");
        getContentPane().add(ajoutUtilGrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        ajoutGrUtilButton.setText("Ajouter");
        getContentPane().add(ajoutGrUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        searchGrLabel.setText("Recherche");
        getContentPane().add(searchGrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 20));

        searchUtilLabel.setText("Recherche");
        getContentPane().add(searchUtilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, 20));

        searchUtilAjoutCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(searchUtilAjoutCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 170, -1));

        searchGrAjoutCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(searchGrAjoutCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 170, -1));

        modifierButton.setText("Modifier");
        modifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButtonActionPerformed(evt);
            }
        });
        getContentPane().add(modifierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void searchGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchGrFieldKeyReleased
        String text = searchGrField.getText();        
        searchJList(text, listeGroupeList, searchGrLabel);
    }//GEN-LAST:event_searchGrFieldKeyReleased

    private void searchRetirerDuGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchRetirerDuGrFieldKeyReleased
        String text = searchRetirerDuGrField.getText();        
        searchJList(text, listeUtilGrList, searchUtilLabel);
    }//GEN-LAST:event_searchRetirerDuGrFieldKeyReleased

    private void searchAjoutUtilGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAjoutUtilGrFieldKeyReleased
        String text = searchAjoutUtilGrField.getText();
        searchCombo(text, searchUtilAjoutCombo);
        
    }//GEN-LAST:event_searchAjoutUtilGrFieldKeyReleased

    private void searchAjoutGrUtilFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAjoutGrUtilFieldKeyReleased
        String text = searchAjoutGrUtilField.getText();
        searchCombo(text, searchGrAjoutCombo);
    }//GEN-LAST:event_searchAjoutGrUtilFieldKeyReleased

    private void supprGrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprGrButtonActionPerformed
        int index = listeGroupeList.getSelectedIndex();
        listeModeleGr.remove(index);
        listeGroupeList.setModel(listeModeleGr);
    }//GEN-LAST:event_supprGrButtonActionPerformed

    private void modifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButtonActionPerformed
        String nouvNom = modifNomField.getText();
        //Verification des doublons
        boolean trouve = false;
        for(int i = 0; i < listeModeleGr.size(); i++){
            if(nouvNom.equals(listeModeleGr.get(i))){
                trouve = true;
                i = listeModeleGr.size() + 1;
                JOptionPane.showMessageDialog(null, "Ce nom existe déjà");
            }
        }
        if(!trouve){
           int index = listeGroupeList.getSelectedIndex();
           listeModeleGr.set(index, nouvNom);
           listeGroupeList.setModel(listeModeleGr);
        }
        
    }//GEN-LAST:event_modifierButtonActionPerformed
    public void searchJList(String text, JList liste, JLabel label) {
        
        // Get number of items in the list
        int size = liste.getModel().getSize();
        // Get all item objects
        for (int i = 0; i < size; i++) {
            String item = (String) liste.getModel().getElementAt(i);
            if(item.contains(text)) {
            int index = i;
            liste.setSelectedIndex(index);
            label.setText(text + " trouvé à l'index " + index);
            //Une fois trouvé, on arrête la boucle
            i = size +1;
            } else {
                liste.clearSelection();
                label.setText(text + " non trouvé");
            }
        }        
    }
    
    public void searchCombo(String text, JComboBox box) {
        
        // Get number of items in the list
        int size = box.getModel().getSize();
        
        // Get all item objects
        for (int i = 0; i < size; i++) {
            String item = (String) box.getModel().getElementAt(i);
            if(item.contains(text)) {
            int index = i;
            box.setSelectedIndex(index);
            //label.setText(text + " trouvé à l'index " + index);
            //Une fois trouvé, on arrête la boucle
            i = size +1;
            } else {
                //label.setText(text + " non trouvé");
            }
        }        
    }
    
    private void setListeModelGr(){
        //Requete pour recuperer tous les groupes
        String req = "SELECT....";
        //ResultSet res = Serveur.requeteBDD(req);
        /*        
        while(res.next()){
            modele.addElement(res.getString("nom"));            
        }
        */
        //A REMPLACER PAR CI DESSUS
        listeModeleGr.addElement("1");
        listeModeleGr.addElement("2");
        //
        listeGroupeList.setModel(listeModeleGr);
    }
    
    private void setListeModelUtil(){
        int index = listeUtilGrList.getSelectedIndex();
        
        /*        
        while(res.next()){
            modele.addElement(res.getString("prenom") + " " + res.getString("nom"));            
        }
        */
        //A REMPLACER PAR CI DESSUS
        listeModeleUtil.addElement("1");
        listeModeleUtil.addElement("2");
        //
        listeUtilGrList.setModel(listeModeleUtil);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurGestGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreServeurGestGroupe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepterButton;
    private javax.swing.JButton ajoutGrUtilButton;
    private javax.swing.JLabel ajoutGrUtilLabel;
    private javax.swing.JButton ajoutUtilGrButton;
    private javax.swing.JLabel ajoutUtilGrLabel;
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane listeGrList;
    private javax.swing.JList<String> listeGroupeList;
    private javax.swing.JList<String> listeUtilGrList;
    private javax.swing.JTextField modifNomField;
    private javax.swing.JLabel modifNomLabel;
    private javax.swing.JButton modifierButton;
    private javax.swing.JLabel paramGrLabel;
    private javax.swing.JButton retirerDuGrButton;
    private javax.swing.JTextField searchAjoutGrUtilField;
    private javax.swing.JTextField searchAjoutUtilGrField;
    private javax.swing.JComboBox<String> searchGrAjoutCombo;
    private javax.swing.JTextField searchGrField;
    private javax.swing.JLabel searchGrLabel;
    private javax.swing.JTextField searchRetirerDuGrField;
    private javax.swing.JComboBox<String> searchUtilAjoutCombo;
    private javax.swing.JLabel searchUtilLabel;
    private javax.swing.JLabel supprDuGroupeLabel;
    private javax.swing.JButton supprGrButton;
    // End of variables declaration//GEN-END:variables
}
