/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import serveur.Serveur;

/**
 *
 * @author Lucas
 */
public class FenetreServeurAccueil extends javax.swing.JFrame {
    private Serveur serveur;
    /**
     * Creates new form FenetreServeurAccueil
     */
    public FenetreServeurAccueil(Serveur serveur) {
        this.serveur = serveur;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        creerGroupeButton = new javax.swing.JButton();
        supprModGroupeButton = new javax.swing.JButton();
        groupeLabel = new javax.swing.JLabel();
        utilLabel = new javax.swing.JLabel();
        creerUtilButton = new javax.swing.JButton();
        supprModUtilButton = new javax.swing.JButton();
        decoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu serveur");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        creerGroupeButton.setText("Créer un groupe");
        creerGroupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerGroupeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 80, 0, 0);
        getContentPane().add(creerGroupeButton, gridBagConstraints);

        supprModGroupeButton.setText("Supprimer / Modifier");
        supprModGroupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprModGroupeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 70, 82, 0);
        getContentPane().add(supprModGroupeButton, gridBagConstraints);

        groupeLabel.setText("Gestion des groupes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 80, 0, 0);
        getContentPane().add(groupeLabel, gridBagConstraints);

        utilLabel.setText("Gestion des utilisateurs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 71, 0, 0);
        getContentPane().add(utilLabel, gridBagConstraints);

        creerUtilButton.setText("Créer un utilisateur");
        creerUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerUtilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 61, 0, 0);
        getContentPane().add(creerUtilButton, gridBagConstraints);

        supprModUtilButton.setText("Supprimer / Modifier");
        supprModUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprModUtilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 61, 82, 0);
        getContentPane().add(supprModUtilButton, gridBagConstraints);

        decoButton.setText("Déconnexion");
        decoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 11, 0, 25);
        getContentPane().add(decoButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerGroupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerGroupeButtonActionPerformed
        FenetreServeurCreerGr fenetre = new FenetreServeurCreerGr(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_creerGroupeButtonActionPerformed

    private void supprModGroupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprModGroupeButtonActionPerformed
        FenetreServeurGestGroupe fenetre = new FenetreServeurGestGroupe(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_supprModGroupeButtonActionPerformed

    private void creerUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerUtilButtonActionPerformed
        FenetreServeurCreerUtil fenetre = new FenetreServeurCreerUtil(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_creerUtilButtonActionPerformed

    private void supprModUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprModUtilButtonActionPerformed
        FenetreServeurGestUtil fenetre = new FenetreServeurGestUtil(serveur);
        fenetre.setVisible(true);
    }//GEN-LAST:event_supprModUtilButtonActionPerformed

    private void decoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoButtonActionPerformed
        serveur.deconnecterServeur();
        FenetreServeurConnexion fen = new FenetreServeurConnexion();
        fen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_decoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreServeurAccueil().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creerGroupeButton;
    private javax.swing.JButton creerUtilButton;
    private javax.swing.JButton decoButton;
    private javax.swing.JLabel groupeLabel;
    private javax.swing.JButton supprModGroupeButton;
    private javax.swing.JButton supprModUtilButton;
    private javax.swing.JLabel utilLabel;
    // End of variables declaration//GEN-END:variables
}
