/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import modele.Groupe;
import modele.Utilisateur;
import serveur.Serveur;

/**
 *
 * @author Lucas
 */
public class FenetreServeurGestGroupe extends javax.swing.JFrame {
    private DefaultListModel listeModeleUtil;
    private DefaultListModel listeModeleGr;
    private DefaultComboBoxModel comboGrModele;
    private DefaultComboBoxModel comboUtilModele;
    private List<Utilisateur> listeUtil;
    private Groupe groupeSelect;
    private boolean grModifie;
    private Serveur serveur;
    /**
     * Creates new form FenetreServeurGestGroupe
     */
    public FenetreServeurGestGroupe(Serveur serveur) {
        this.serveur = serveur;
        listeUtil = new ArrayList();
        groupeSelect = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paramGrLabel = new javax.swing.JLabel();
        listeGrList = new javax.swing.JScrollPane();
        listeGroupeList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeUtilGrList = new javax.swing.JList<>();
        searchGrField = new javax.swing.JTextField();
        supprGrButton = new javax.swing.JButton();
        modifNomLabel = new javax.swing.JLabel();
        modifNomField = new javax.swing.JTextField();
        accepterButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ajoutUtilGrLabel = new javax.swing.JLabel();
        ajoutGrUtilLabel = new javax.swing.JLabel();
        supprDuGroupeLabel = new javax.swing.JLabel();
        searchRetirerDuGrField = new javax.swing.JTextField();
        searchAjoutUtilGrField = new javax.swing.JTextField();
        searchAjoutGrUtilField = new javax.swing.JTextField();
        retirerDuGrButton = new javax.swing.JButton();
        ajoutUtilGrButton = new javax.swing.JButton();
        ajoutGrUtilButton = new javax.swing.JButton();
        searchGrLabel = new javax.swing.JLabel();
        searchUtilLabel = new javax.swing.JLabel();
        ajoutUtilCombo = new javax.swing.JComboBox<>();
        ajoutGrCombo = new javax.swing.JComboBox<>();
        modifierButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de groupes");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        paramGrLabel.setText("Liste des groupes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 49, 0, 0);
        getContentPane().add(paramGrLabel, gridBagConstraints);

        listeGroupeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeModeleGr = new DefaultListModel();
        setListeModelGr();
        listeGroupeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeGroupeListValueChanged(evt);
            }
        });
        listeGrList.setViewportView(listeGroupeList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 0, 0);
        getContentPane().add(listeGrList, gridBagConstraints);

        listeUtilGrList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeModeleUtil = new DefaultListModel();
        setListeModelUtil();
        jScrollPane1.setViewportView(listeUtilGrList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.ipady = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 309, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        searchGrField.setText("search");
        searchGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchGrFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        getContentPane().add(searchGrField, gridBagConstraints);

        supprGrButton.setText("Supprimer");
        supprGrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprGrButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 0, 0);
        getContentPane().add(supprGrButton, gridBagConstraints);

        modifNomLabel.setText("Modifier le nom :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 0, 0);
        getContentPane().add(modifNomLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 50, 0, 0);
        getContentPane().add(modifNomField, gridBagConstraints);

        accepterButton.setText("Accepter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 40, 0, 0);
        getContentPane().add(accepterButton, gridBagConstraints);

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 7, 0, 0);
        getContentPane().add(annulerButton, gridBagConstraints);

        jLabel1.setText("Liste des utilisateurs du groupe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 289, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        ajoutUtilGrLabel.setText("Ajouter un utilisateur :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 299, 0, 0);
        getContentPane().add(ajoutUtilGrLabel, gridBagConstraints);

        ajoutGrUtilLabel.setText("Ajouter les utilisateurs d'un groupe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 299, 0, 26);
        getContentPane().add(ajoutGrUtilLabel, gridBagConstraints);

        supprDuGroupeLabel.setText("Supprimer du groupe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 319, 0, 0);
        getContentPane().add(supprDuGroupeLabel, gridBagConstraints);

        searchRetirerDuGrField.setText("search");
        searchRetirerDuGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchRetirerDuGrFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 299, 0, 0);
        getContentPane().add(searchRetirerDuGrField, gridBagConstraints);

        searchAjoutUtilGrField.setText("search");
        searchAjoutUtilGrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAjoutUtilGrFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 299, 0, 0);
        getContentPane().add(searchAjoutUtilGrField, gridBagConstraints);

        searchAjoutGrUtilField.setText("search");
        searchAjoutGrUtilField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAjoutGrUtilFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 299, 0, 0);
        getContentPane().add(searchAjoutGrUtilField, gridBagConstraints);

        retirerDuGrButton.setText("Supprimer");
        retirerDuGrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerDuGrButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(retirerDuGrButton, gridBagConstraints);

        ajoutUtilGrButton.setText("Ajouter");
        ajoutUtilGrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutUtilGrButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 0, 0);
        getContentPane().add(ajoutUtilGrButton, gridBagConstraints);

        ajoutGrUtilButton.setText("Ajouter");
        ajoutGrUtilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutGrUtilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 0, 0);
        getContentPane().add(ajoutGrUtilButton, gridBagConstraints);

        searchGrLabel.setText("Recherche");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 50, 0, 0);
        getContentPane().add(searchGrLabel, gridBagConstraints);

        searchUtilLabel.setText("Recherche");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 99;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 299, 0, 0);
        getContentPane().add(searchUtilLabel, gridBagConstraints);

        ajoutUtilCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboUtilModele = new DefaultComboBoxModel();
        setComboUtilModel();
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 299, 0, 0);
        getContentPane().add(ajoutUtilCombo, gridBagConstraints);

        ajoutGrCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboGrModele = new DefaultComboBoxModel();
        setComboGrModel();
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 299, 13, 0);
        getContentPane().add(ajoutGrCombo, gridBagConstraints);

        modifierButton.setText("Modifier");
        modifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        getContentPane().add(modifierButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void searchGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchGrFieldKeyReleased
        String text = searchGrField.getText();        
        searchJList(text, listeGroupeList, searchGrLabel);
    }//GEN-LAST:event_searchGrFieldKeyReleased

    private void searchRetirerDuGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchRetirerDuGrFieldKeyReleased
        String text = searchRetirerDuGrField.getText();        
        searchJList(text, listeUtilGrList, searchUtilLabel);
    }//GEN-LAST:event_searchRetirerDuGrFieldKeyReleased

    private void searchAjoutUtilGrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAjoutUtilGrFieldKeyReleased
        String text = searchAjoutUtilGrField.getText();
        searchCombo(text, ajoutUtilCombo);
        
    }//GEN-LAST:event_searchAjoutUtilGrFieldKeyReleased

    private void searchAjoutGrUtilFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAjoutGrUtilFieldKeyReleased
        String text = searchAjoutGrUtilField.getText();
        searchCombo(text, ajoutGrCombo);
    }//GEN-LAST:event_searchAjoutGrUtilFieldKeyReleased

    private void supprGrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprGrButtonActionPerformed
        int index = listeGroupeList.getSelectedIndex();
        listeModeleGr.remove(index);
        listeGroupeList.setModel(listeModeleGr);
        int response = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            //On supprime le groupe
            //TODO
        }
        
    }//GEN-LAST:event_supprGrButtonActionPerformed

    private void modifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment modifier ce groupe ?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            String nouvNom = modifNomField.getText();
            //Verification des doublons
            boolean trouve = false;
            for(int i = 0; i < listeModeleGr.size(); i++){
                if(nouvNom.equals(listeModeleGr.get(i))){
                    trouve = true;
                    i = listeModeleGr.size() + 1;
                    JOptionPane.showMessageDialog(null, "Ce nom existe déjà");
                }
            }
            if(!trouve){
               //On envoie au serveur les modif
               //TODO listeUtil
               //rafraichir la liste des groupes
               setListeModelGr();               
            }
        }        
        
    }//GEN-LAST:event_modifierButtonActionPerformed

    private void retirerDuGrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerDuGrButtonActionPerformed
        int index = listeUtilGrList.getSelectedIndex();
        listeModeleGr.remove(index);
        listeUtilGrList.setModel(listeModeleGr);
        //On supprime l'utilisateur à l'index index car l'ordre est le même
        listeUtil.remove(index);        
    }//GEN-LAST:event_retirerDuGrButtonActionPerformed

    private void listeGroupeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeGroupeListValueChanged
        //Si un autre groupe était deja selectionné (liste util non vide) et modifications ont eu lieu
        if((groupeSelect != null) && grModifie){
            int response = JOptionPane.showConfirmDialog(null, "Voulez-vous sauvegarder ?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                //On modifie le groupe
            
                //TODO
            }
            //sinon on n'envoie rien au serveur
        }
        grModifie = false;
        listeGroupeList.removeAll();
        int indGrSelect = listeGroupeList.getSelectedIndex();
        groupeSelect = (Groupe) listeModeleGr.get(indGrSelect);
        //On affiche la liste du nouveau groupe selectionné
        
        setListeModelUtil();
    }//GEN-LAST:event_listeGroupeListValueChanged

    private void ajoutUtilGrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutUtilGrButtonActionPerformed
        if(!listeModeleUtil.contains(ajoutUtilCombo.getSelectedItem())){
            listeModeleUtil.addElement(ajoutUtilCombo.getSelectedItem());
            listeUtilGrList.setModel(listeModeleUtil);
            listeUtil.add((Utilisateur) ajoutUtilCombo.getSelectedItem());
        }
    }//GEN-LAST:event_ajoutUtilGrButtonActionPerformed

    private void ajoutGrUtilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutGrUtilButtonActionPerformed
        String nomGr = (String) ajoutGrCombo.getSelectedItem();
        
        Groupe gr = null;
        try {
            gr = serveur.getGroupeFromNomGroupe(nomGr);
        } catch (SQLException ex) {
            Logger.getLogger(FenetreServeurGestGroupe.class.getName()).log(Level.SEVERE, null, ex);
        }
        //On recupère les utilisateurs du groupe qu'on veut fusionner
        List<Utilisateur> utils = gr.getListeUtilisateur();
        //On get la liste correspondant au groupe dans lequel on est
        
        for(Utilisateur ut : utils){
            if(!listeModeleUtil.contains(ut)){
                listeModeleUtil.addElement(ut);
                //On ajoute l'utilisateur à la liste
                listeUtil.add((Utilisateur) ut);                
            }
        }
        listeUtilGrList.setModel(listeModeleUtil); 
    }//GEN-LAST:event_ajoutGrUtilButtonActionPerformed
    public void searchJList(String text, JList liste, JLabel label) {
        
        // Get number of items in the list
        int size = liste.getModel().getSize();
        // Get all item objects
        for (int i = 0; i < size; i++) {
            String item = (String) liste.getModel().getElementAt(i);
            if(item.contains(text)) {
            int index = i;
            liste.setSelectedIndex(index);
            label.setText(text + " trouvé à l'index " + index);
            //Une fois trouvé, on arrête la boucle
            i = size +1;
            } else {
                liste.clearSelection();
                label.setText(text + " non trouvé");
            }
        }        
    }
    
    public void searchCombo(String text, JComboBox box) {
        
        // Get number of items in the list
        int size = box.getModel().getSize();
        
        // Get all item objects
        for (int i = 0; i < size; i++) {
            String item = (String) box.getModel().getElementAt(i);
            if(item.contains(text)) {
            int index = i;
            box.setSelectedIndex(index);
            //label.setText(text + " trouvé à l'index " + index);
            //Une fois trouvé, on arrête la boucle
            i = size +1;
            } else {
                //label.setText(text + " non trouvé");
            }
        }        
    }
    
    private void setListeModelGr(){
       
        Set<String> groupes = serveur.getGroupes();
        //Ajout de chaque groupe dans la JList
        for(String gr : groupes){
            listeModeleGr.addElement(gr);
        }
        listeGroupeList.setModel(listeModeleGr);        
    }
    
    private void setListeModelUtil(){
        String nomGr = listeUtilGrList.getSelectedValue();
        if(nomGr != null){
            Groupe gr = null;
            try {
                gr = serveur.getGroupeFromNomGroupe(nomGr);
                listeUtil = gr.getListeUtilisateur();
                //Ajout de chaque utilisateur dans la JList
                for(Utilisateur ut : listeUtil){
                    listeModeleUtil.addElement(ut);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FenetreServeurGestGroupe.class.getName()).log(Level.SEVERE, null, ex);
            }
               
            listeUtilGrList.setModel(listeModeleUtil);
        }
        
    }
    
    private void setComboGrModel(){
        
        Set<String> groupes = serveur.getGroupes();
        for(String gr : groupes){
            comboGrModele.addElement(gr);
        }
        ajoutGrCombo.setModel(comboGrModele);        
    }
    
    private void setComboUtilModel(){
        
        Set<Utilisateur> utils = serveur.getUtilisateurs();
        for(Utilisateur ut : utils){
            comboUtilModele.addElement(ut);
        }
        ajoutUtilCombo.setModel(comboUtilModele);        
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepterButton;
    private javax.swing.JComboBox<String> ajoutGrCombo;
    private javax.swing.JButton ajoutGrUtilButton;
    private javax.swing.JLabel ajoutGrUtilLabel;
    private javax.swing.JComboBox<String> ajoutUtilCombo;
    private javax.swing.JButton ajoutUtilGrButton;
    private javax.swing.JLabel ajoutUtilGrLabel;
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane listeGrList;
    private javax.swing.JList<String> listeGroupeList;
    private javax.swing.JList<String> listeUtilGrList;
    private javax.swing.JTextField modifNomField;
    private javax.swing.JLabel modifNomLabel;
    private javax.swing.JButton modifierButton;
    private javax.swing.JLabel paramGrLabel;
    private javax.swing.JButton retirerDuGrButton;
    private javax.swing.JTextField searchAjoutGrUtilField;
    private javax.swing.JTextField searchAjoutUtilGrField;
    private javax.swing.JTextField searchGrField;
    private javax.swing.JLabel searchGrLabel;
    private javax.swing.JTextField searchRetirerDuGrField;
    private javax.swing.JLabel searchUtilLabel;
    private javax.swing.JLabel supprDuGroupeLabel;
    private javax.swing.JButton supprGrButton;
    // End of variables declaration//GEN-END:variables
}
