/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projets5;

/**
 *
 * @author Lucas
 */
public class FenetreServeurCreerUtil extends javax.swing.JFrame {

    /**
     * Creates new form FenetreServeurCreerUtil
     */
    public FenetreServeurCreerUtil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        confirmMdpField = new javax.swing.JTextField();
        nomField = new javax.swing.JTextField();
        prenomField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        mdpField = new javax.swing.JTextField();
        nomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        mdpLabel = new javax.swing.JLabel();
        confirmMdpLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchAjoutGrField = new javax.swing.JTextField();
        ajoutGrUtilButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeGroupesList = new javax.swing.JList<>();
        searchSupprGrField = new javax.swing.JTextField();
        supprGrButton = new javax.swing.JButton();
        creerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Création d'utilisateur");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Paramètres de l'utilisateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 31, -1, -1));
        getContentPane().add(confirmMdpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 110, -1));
        getContentPane().add(nomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, -1));
        getContentPane().add(prenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, -1));
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, -1));
        getContentPane().add(mdpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, -1));

        nomLabel.setText("Nom :");
        getContentPane().add(nomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        prenomLabel.setText("Prenom :");
        getContentPane().add(prenomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        idLabel.setText("Identifiant :");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        mdpLabel.setText("Mot de passe :");
        getContentPane().add(mdpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        confirmMdpLabel.setText("Confirmation :");
        getContentPane().add(confirmMdpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setText("Ajouter un groupe à l'utilisateur :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        getContentPane().add(searchAjoutGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        ajoutGrUtilButton.setText("Ajouter");
        getContentPane().add(ajoutGrUtilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel3.setText("Liste des groupes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        listeGroupesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listeGroupesList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 160, 130));

        searchSupprGrField.setText("search");
        getContentPane().add(searchSupprGrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, -1));

        supprGrButton.setText("Supprimer");
        getContentPane().add(supprGrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        creerButton.setText("Créer");
        creerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(annulerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreServeurCreerUtil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreServeurCreerUtil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutGrUtilButton;
    private javax.swing.JButton annulerButton;
    private javax.swing.JTextField confirmMdpField;
    private javax.swing.JLabel confirmMdpLabel;
    private javax.swing.JButton creerButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeGroupesList;
    private javax.swing.JTextField mdpField;
    private javax.swing.JLabel mdpLabel;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField prenomField;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField searchAjoutGrField;
    private javax.swing.JTextField searchSupprGrField;
    private javax.swing.JButton supprGrButton;
    // End of variables declaration//GEN-END:variables
}
